<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\MiniDisplay.Imaging\MiniDisplay.Imaging.csproj" />
    <ProjectReference Include="..\MiniDisplay.Transport\MiniDisplay.Transport.csproj" />
  </ItemGroup>
</Project>
